name: 'Custom Python Search and Replace'
description: 'Performs search and replace operations in files using Python'
author: 'ChatGPT'
inputs:
  directory:
    description: 'The directory to search for test files'
    required: true
  replacements_json:
    description: 'A JSON array containing replacements'
    required: false
  file_pattern:
    description: 'Regular expression pattern for matching files'
    required: true
  debug:
    description: 'Enable debug mode to print original and modified contents of files'
    required: false
    default: false
  recursive:
    description: 'Control recursive searching for files from the directory'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Set environment variables and run Python script
      env:
        DIRECTORY: ${{ inputs.directory }}
        REPLACEMENTS_JSON: ${{ inputs.replacements_json }}
        FILE_PATTERN: ${{ inputs.file_pattern }}
        DEBUG: ${{ inputs.debug }}
        RECURSIVE_SEARCH: ${{ inputs.recursive }}
      run: |
        echo "$REPLACEMENTS_JSON" > replacements.json
        python $GITHUB_ACTION_PATH/main.py
      shell: bash
