name: Search and Replace Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Search and Replace Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Test Files
        run: |
          echo "This is a test file 1" > ${{ github.workspace }}/test_file1.txt
          echo "This is a test file 2" > ${{ github.workspace }}/test_file2.txt
        shell: bash

      - name: Custom Python Search and Replace
        uses: carefreepineapple/replace-in-files@main
        with:
          directory: '${{ github.workspace }}'
          file_pattern: '^test_file.*\.txt$'
          replacements_json: |
            [
              {"regex": "test", "replacement": "exam"},
              {"regex": "This", "replacement": "that"},
              {"regex": "file \\d+", "replacement": "file new number"}
            ]
          
